spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      restaurant-request-topic: RESTAURANT_REQUEST_TOPIC
      restaurant-response-topic: RESTAURANT_RESPONSE_TOPIC
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.food.ordering.system.common.messaging.*'