spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      payment-process-request: PAYMENT_PROCESS_REQUEST
      payment-process-response: PAYMENT_PROCESS_RESPONSE
      payment-cancel-request: PAYMENT_CANCEL_REQUEST
      payment-cancel-response: PAYMENT_CANCEL_RESPONSE
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.food.ordering.system.common.messaging.*'